version: "3"
services:
  sftp:
    container_name: sftp
    image: atmoz/sftp:alpine
    volumes:
      # Providing your own SSH host key
      - ../mnt/home/ssh_host_rsa_key.pub:/etc/ssh/ssh_host_rsa_key.pub:ro
      - ../mnt/home/ssh_host_ed25519_key.pub:/etc/ssh/ssh_host_ed25519_key.pub:ro
      # Testing add own SSH key to user dir
      - ../mnt/home/ssh_host_rsa_key.pub:/home/${SFTP_USER}/.ssh/keys/ssh_host_rsa_key.pub:ro"
      - ../mnt/home/ssh_host_ed25519_key.pub:/home/${SFTP_USER}/.ssh/keys/ssh_host_ed25519_key.pub:ro"
      # Mount data path
      - ../mnt/home/${DATA_STORE}:/home/${SFTP_USER}/${DATA_STORE}
      # Execute custom scripts or applications
      - ./scripts/sftp_init.sh:/etc/sftp.d/init.sh:ro
    ports:
      - "2222:22"
    environment:
      - SFTP_USERS=${SFTP_USER}:${SFTP_PASS}:1001::${DATA_STORE}
    restart: always
    # # NOTE: syntax: user:password[:e][:uid[:gid[:dir1[,dir2]...]]]
    # command: |
    #     ${SFTP_USER}:${SFTP_PASS}:1001::${DATA_STORE}
