version: "3"
services:
  minio:
    container_name: minio
    image: bitnami/minio:2024
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=${MINIO_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_PASS}
      - MINIO_DEFAULT_BUCKETS=${MINIO_BUCKET}
    volumes:
      - ../mnt/minio_data:/bitnami/minio/data
