version: "3"
services:
    postgres:
        container_name: postgres
        image: postgres:13-alpine
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASS=${POSTGRES_PASS}
            - POSTGRES_DB=${POSTGRES_DB}
#        ports:
#            - "5432:5432"
#        # Use a persistent volume to store data. As mentioned above,
#        # without a persistent volume, you’ll lose data if the
#        # container restarts.
#        volumes:
#            - ./mnt/postgres-data:/var/lib/postgresql/data
#            - ./scripts/pg-extensions:/docker-entrypoint-initdb.d
#        # Enable
#        # 1) CREATE EXTENSION pg_stat_statements;
#        # 2) ALTER SYSTEM SET shared_preload_libraries='pg_stat_statements';
#        # 3) Restart Database
#        command: |
#            postgres
#                -c shared_preload_libraries='pg_stat_statements'
#                -c pg_stat_statements.track=all
#                -c max_connections=200
#        healthcheck:
#            test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres -d postgres'"]
#            interval: 10s
#            timeout: 5s
#            retries: 5
